### PR TITLE
Destination endpoints

### PR DESCRIPTION
**Pull request by mugberto**
This PR submits modifications made to the json response of the destination endpoints

### CODE REVIEW

**Review by AleksandarIvezic — APPROVED** [review]
Hi @mugberto ,

Everything looks fine by my side. I approve the changes. ✔️ ✔️ ✔️ 
You can merge the branch.

Cheers!!! 🥂

**Review by themonster2015 — CHANGES_REQUESTED** [review]
Hi @mugberto , good job so far. However, there is a small issue. The json data response for all destinations still doesn't have the id.

**Review by danmainah — APPROVED** [review]
Good job @mugberto 

Project Approved  ✔✔✔

**Comment by AleksandarIvezic** [comment]
Hi @mugberto , @yen,

We decided to approve this project so we don't prolonge the whole work. We can add id in another patch.

**Pull request merged**
